apt install -y git
apt install -y gcc 
apt install -y gawk 
apt install -y flex
apt install -y libc6:i386
apt install -y libstdc++6:i386
apt install -y lib32z1
apt install -y libncurses5
apt install -y libncurses5-dev
apt install -y python
apt install -y g++
apt install -y libz-dev
apt install -y libssl-dev
apt install -y make
apt install -y p7zip-full
